### ISSUE TITLE
Can I only use llama/llama 2? 

### ISSUE THREAD

**Issue by batindfa** [ora-io/opml#3]
Can I use other LLm, like mistral? 
If so, what do I need to modify? Thanks!

**Comment by babytdream** [comment]
same question

**Comment by meneramandarin** [comment]
currently you can only use llama2 and stable diffusion. but we're adding more models as we go along.

**Comment by babytdream** [comment]
@meneramandarin hi, can I use the fine-tuned llama2 model?

**Comment by meneramandarin** [comment]
Right now we dont accept any custom models for opML unless you implement it by yourself.

**Comment by babytdream** [comment]
@meneramandarin 
Hello, I can't run `bash ./demo/challenge_llama.sh` on my computer, Do you know the problem? Thanks!
1. I have download `llama-7b-fp32.bin `in `opml/mlgo/examples/llama/models`, and can run this commad:` ./llama --threads 8 --model ./models/llama-7b-fp32.bin --temp 0.80 --context 128 --predict 128 --prompt "How to combine AI and blockchain?"`
![image](https://github.com/hyperoracle/opml/assets/74184102/07b591d4-8a4e-4047-9adb-417f9eed2f25)

2.But when I run `bash ./demo/challenge_llama.sh`, it appears this error:
![image](https://github.com/hyperoracle/opml/assets/74184102/cbb2179f-29f4-4458-888e-483f893627ea)

**Comment by babytdream** [comment]
@meneramandarin 
Hello, What can I do to make api calls(https://www.hyperoracle.io/app/opml/llm)?Thanks!
I have successfully run this command: `bash ./demo/challenge_simple.sh`

**Comment by fewwwww** [comment]
Hi we will soon release API this week.

**Comment by fewwwww** [comment]
You can use our OAO (Onchain AI Oracle) for making "API" calls directly onchain.
