### ISSUE TITLE
Can the results of AI model inference be sent to the chain?

### ISSUE THREAD

**Issue by babytdream** [ora-io/opml#4]
Can I deploy opml to a blockchain testnet?
Can the results of AI model inference be sent to the chain? What command to use?Thanks！

**Comment by yanmengxiang1** [comment]
I also want to test a blockchain testnet, but cant't do it?
I suspect the AI model is fake.

**Comment by fewwwww** [comment]
Currently only local testnets are supported. So public testnets will be supported soon.

**Comment by babytdream** [comment]
@fewwwww Hi, in the  local testnets, I could not find the results of AI model inference be sent to the chain？
This is the transaction record on the test chain. Do you have time to take a look? Thank you！
[本地测试环境.txt](https://github.com/hyperoracle/opml/files/14133386/default.txt)

**Comment by fewwwww** [comment]
> @fewwwww Hi, in the local testnets, I could not find the results of AI model inference be sent to the chain？ This is the transaction record on the test chain. Do you have time to take a look? Thank you！ [local test.txt](https://github.com/hyperoracle/opml/files/14133392/local.test.txt)

Hi, I think the file contains multiple txs showing that the challenge are sent to the chain. For example: all the contract calls to "LayeredChallenge"

**Comment by babytdream** [comment]
@fewwwww Thanks!
But in https://github.com/hyperoracle/opml/blob/main/docs/OPML.md#:~:text=The%20requester%20first,results%20on%20chain,
`The server then finishes the ML service task and commits results on chain.` (I haven’t seen this implementation method in this project. Can you help explain it?)

**Comment by batindfa** [comment]
any progress? 

> @fewwwww Thanks! I want to look the results of llama inference be sent to the chain. In https://github.com/hyperoracle/opml/blob/main/docs/OPML.md#:~:text=The%20requester%20first,results%20on%20chain, `The server then finishes the ML service task and commits results on chain.` (I haven’t seen this implementation method in this project. Can you help explain it?)

**Comment by fewwwww** [comment]
Ok, I get what you mean. You want to see the result of AI inference on chain.

So currently in this repo, it is mainly for showing the idea and implementation of the challenge and fault proof system of opML. It doesn't provide this function, cause the inference actually lives in the "Layer2 layer", not on the base layer blockchain.

We will release some work in the future enabling the feature you request.
