### ISSUE TITLE
Something went wrong! ERROR :Cannot read properties of undefined (reading 'MPChallenge')

### ISSUE THREAD

**Issue by oktaykurt** [ora-io/opml#6]
Generating prompts returns "reading 'MPChallenge" error on the https://www.ora.io/app/opml/sd page. 
<img width="1200" alt="Screenshot 2024-02-29 at 15 11 39" src="https://github.com/ora-io/opml/assets/10723547/f98cd58c-fb7f-4441-b5ac-338e2f5fcf65">

**Comment by 0x1cc** [comment]
I sincerely apologize for the inconvenience caused by this error. Thank you for bringing this to our attention. Our team is actively working to fix this bug, ensuring long-term stability. We appreciate your understanding.
